# Generated by Django 3.1.4 on 2021-01-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number_of_hours', models.FloatField(null=True)),
                ('schedule', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Управление', 'Управление'), ('Инженерия', 'Инженерия'), ('Языки', 'Языки')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Начался', 'Начался'), ('Не начался', 'Не начался')], max_length=50, null=True)),
            ],
        ),
    ]
