# Generated by Django 3.1.4 on 2021-01-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courses_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.courses'),
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
    ]
